### PR TITLE
metrics: supply the metric on storage usage.

### PR DESCRIPTION
**Pull request by LykxSassinator**
## Description
This pr is used to supply the necessary metric on storage usage of engine.

### CODE REVIEW

**Review by tabokie — COMMENTED** [review]
Why is this needed? `raft_engine_log_file_count * file_size` should be equivalent. If needed you can publish file_size via a separate counter.

**Comment by LykxSassinator** [comment]
> Why is this needed? `raft_engine_log_file_count * file_size` should be equivalent. If needed you can publish file_size via a separate counter.

From users, they think the usage of raft-engine is not clear as expected. They expect the storage size can be easily checked.

**Comment by tabokie** [comment]
> > Why is this needed? `raft_engine_log_file_count * file_size` should be equivalent. If needed you can publish file_size via a separate counter.
> 
> From users, they think the usage of raft-engine is not clear as expected. They expect the storage size can be easily checked.

You can either add a counter for raft-engine file_size config in TiKV, then use `file_count * file_size` to display the size. Or manually flush the metrics in TiKV's `EngineMetricsManager`. The information is already there, I don't think it's worth adding another counter to raft-engine.

**Pull request closed without merging**
