### PR TITLE
A weird problem

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

### CODE REVIEW

**Comment by Fullstop000** [comment]
This looks confusing /cc @hicqu

**Comment by hicqu** [comment]
The reason is `MemTableAccessor::collect`. This method will scan all slots in `MemTableAccessor`. In your change all slots reference to one same hashmap, so that the method can return duplicate memtables. Rewrite a memtable twice causes the panic.

**Comment by hicqu** [comment]
And in `MemTable::fetch_rewrite_entries`, the check logic should be updated for this case. I will send a PR for this later.

**Comment by hicqu** [comment]
I think it can be closed now.

**Pull request closed without merging**
